### ISSUE TITLE
Logs are duplicated on initial load of Sandpack

### ISSUE THREAD

**Issue by iampava** [codesandbox/sandpack#856]
# Bug report

## Packages affected

-   [ ] sandpack-client
-   [x] sandpack-react

## Description of the problem
I'm running a simple code that does `console.log("smth");`. The `<SandpackConsole>` shows the text twice (only at initial load).

### What steps can we take to reproduce the problem?

Navigate to the CodeSandbox code below. You'll see the text `smth` displayed twice.

NOTE: even if I set the `resetOnPreviewRestart` flag to `true`, the problem still persists.

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |2.1.10|
| Sandpack-react version  |2.1.10|
| Browser                 |Firefox, Chrome|
| Operating System        |Mac OS Ventura|

**Comment by iampava** [comment]
A "hack" i found that solves the problem is to

1. Set initially `recompileMode: "immediate"`
2. Listen to the `success` message
3. Once that's emitted, change `recompileMode: "delayed"`

**Comment by danilowoz** [comment]
It has been fixed on the lasted version. 
Thanks for reporting it

**Comment by panzerdp** [comment]
@danilowoz First, thanks for the wonderful Sandpack: I really like it.

Regarding the double `console.log()`: could you check the [demo](https://codesandbox.io/s/sandpack-double-logs-forked-ennc8s?file=/src/App.js) (vanilla js template, Sandbpack version `2.6.1`)? I still see the double logs.

**Comment by danilowoz** [comment]
Hey, I see only one log. Do you see anything different from that? 

<img width="672" alt="Screenshot 2023-04-17 at 13 33 20" src="https://user-images.githubusercontent.com/4838076/232551657-0f4d651d-9f10-42d9-9b85-b72d3d249d83.png">

**Comment by panzerdp** [comment]
<img width="801" alt="Screenshot 2023-04-17 at 18 41 26" src="https://user-images.githubusercontent.com/1078719/232553466-5498c7ff-319b-45bc-8654-dc09743a2a5a.png">

I see 2 logs (macOS Ventura, Chrome v112).

**Comment by iampava** [comment]
It doesn't reproduce for me on the sandbox I sent above: https://codesandbox.io/s/sandpack-double-logs-nq68bm?file=/src/App.js

**Comment by nrthbound** [comment]
I'm still seeing this using the Vanilla JS template. Any time it re-reads the `index.js`, the `console.log` runs two times, even if it's only being called once. If I reload the entire project, it shows up correctly, but the minute I change anything in the JS, in runs it twice.
